### ISSUE TITLE
missing website: https://ada.yaml.io/

### ISSUE THREAD

**Issue by jrmarino** [yaml/AdaYaml#11]
The referenced website has been missing for at least a month.  Will it be replaced or restored?  If not, the project description should be changed.

**Comment by flyx** [comment]
I moved servers, @ingy hasn't updated the DNS record yet. Site will hopefully be available again soon.

**Comment by jrmarino** [comment]
I guess "soon" is relative ...

**Comment by flyx** [comment]
It always is on projects depending on spare time of their owners :/.

Site is up again now.
